/**
 * Model Hub catalog (Prompt 006B).
 *
 * The catalog is authoritative in code so it cannot drift from the runtime. The
 * db `ai_models` / `ai_model_providers` tables mirror this for future
 * admin-managed editing. `modelId` is globally unique so it can be used as a key.
 *
 * PRICING IS AN APPROXIMATE SNAPSHOT. It may vary by provider, region, discounts,
 * caching, and enterprise agreement, and is NOT a guarantee. Always verify with
 * the provider before relying on it for billing.
 */

import type { ProviderSlug } from "@/lib/db/types";
import type { AiModel, ModelProvider } from "@/modules/model-gateway/types";

/** Snapshot date for all pricing below (kept static so the catalog is pure). */
const PRICE_CHECKED_AT = "2026-07-01T00:00:00.000Z";

export const MODEL_PROVIDERS: ModelProvider[] = [
  {
    slug: "openai",
    displayName: "OpenAI",
    providerType: "openai",
    status: "available",
    defaultBaseUrl: "https://api.openai.com/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://platform.openai.com/docs",
    platformKeyEnvVar: "OPENAI_API_KEY",
  },
  {
    slug: "anthropic",
    displayName: "Anthropic",
    providerType: "anthropic",
    status: "available",
    defaultBaseUrl: "https://api.anthropic.com/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://docs.anthropic.com",
    platformKeyEnvVar: "ANTHROPIC_API_KEY",
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek",
    providerType: "openai_compatible",
    status: "available",
    defaultBaseUrl: "https://api.deepseek.com/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://api-docs.deepseek.com",
    platformKeyEnvVar: "DEEPSEEK_API_KEY",
  },
  {
    slug: "moonshot_kimi",
    displayName: "Moonshot Kimi",
    providerType: "openai_compatible",
    status: "available",
    defaultBaseUrl: "https://api.moonshot.ai/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://platform.moonshot.ai/docs",
    platformKeyEnvVar: "MOONSHOT_API_KEY",
  },
  {
    slug: "groq",
    displayName: "Groq",
    providerType: "openai_compatible",
    status: "available",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://console.groq.com/docs",
    platformKeyEnvVar: "GROQ_API_KEY",
  },
  {
    slug: "google_gemini",
    displayName: "Google Gemini",
    providerType: "google",
    status: "available",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://ai.google.dev/docs",
    platformKeyEnvVar: "GOOGLE_GENERATIVE_AI_API_KEY",
  },
  {
    slug: "fireworks",
    displayName: "Fireworks",
    providerType: "openai_compatible",
    status: "available",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    supportsPlatformKey: true,
    supportsByok: true,
    documentationUrl: "https://docs.fireworks.ai",
    platformKeyEnvVar: "FIREWORKS_API_KEY",
  },
  {
    slug: "custom_openai_compatible",
    displayName: "Custom (OpenAI-compatible)",
    providerType: "openai_compatible",
    status: "available",
    defaultBaseUrl: null,
    supportsPlatformKey: false,
    supportsByok: true,
    documentationUrl: null,
    platformKeyEnvVar: null,
  },
];

/** Default capability set; each model overrides the flags it needs. */
type ModelSeed = Omit<
  AiModel,
  | "status"
  | "supportsText"
  | "supportsVision"
  | "supportsAudio"
  | "supportsTools"
  | "supportsJson"
  | "supportsStreaming"
  | "supportsReasoning"
  | "supportsCaching"
  | "priceCheckedAt"
> &
  Partial<
    Pick<
      AiModel,
      | "status"
      | "supportsText"
      | "supportsVision"
      | "supportsAudio"
      | "supportsTools"
      | "supportsJson"
      | "supportsStreaming"
      | "supportsReasoning"
      | "supportsCaching"
    >
  >;

function model(seed: ModelSeed): AiModel {
  return {
    status: "available",
    supportsText: true,
    supportsVision: false,
    supportsAudio: false,
    supportsTools: false,
    supportsJson: false,
    supportsStreaming: false,
    supportsReasoning: false,
    supportsCaching: false,
    priceCheckedAt: PRICE_CHECKED_AT,
    ...seed,
  };
}

const PRICING_NOTE = "Approximate snapshot; verify with the provider.";

export const AI_MODELS: AiModel[] = [
  // --- OpenAI --------------------------------------------------------------
  model({
    providerSlug: "openai",
    modelId: "gpt-5.5",
    displayName: "GPT-5.5",
    modelFamily: "gpt-5",
    modelTier: "premium",
    recommendedFor: "Highest-quality reasoning, complex analysis, vision",
    contextWindowTokens: 400_000,
    maxOutputTokens: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 5,
    cachedInputUsdPerMillionTokens: 0.5,
    outputUsdPerMillionTokens: 15,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://openai.com/pricing",
  }),
  model({
    providerSlug: "openai",
    modelId: "gpt-5.4",
    displayName: "GPT-5.4",
    modelFamily: "gpt-5",
    modelTier: "balanced",
    recommendedFor: "Everyday work with strong quality and speed",
    contextWindowTokens: 400_000,
    maxOutputTokens: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 2.5,
    cachedInputUsdPerMillionTokens: 0.25,
    outputUsdPerMillionTokens: 10,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://openai.com/pricing",
  }),
  model({
    providerSlug: "openai",
    modelId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    modelFamily: "gpt-5",
    modelTier: "economy",
    recommendedFor: "High-volume, cost-sensitive tasks",
    contextWindowTokens: 400_000,
    maxOutputTokens: 64_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.15,
    cachedInputUsdPerMillionTokens: 0.015,
    outputUsdPerMillionTokens: 0.6,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://openai.com/pricing",
  }),
  model({
    providerSlug: "openai",
    modelId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    modelFamily: "gpt-5",
    modelTier: "economy",
    recommendedFor: "Lightweight classification and routing",
    contextWindowTokens: 256_000,
    maxOutputTokens: 32_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.05,
    cachedInputUsdPerMillionTokens: 0.005,
    outputUsdPerMillionTokens: 0.4,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://openai.com/pricing",
  }),
  model({
    providerSlug: "openai",
    modelId: "gpt-realtime-2",
    displayName: "GPT Realtime 2",
    modelFamily: "gpt-realtime",
    modelTier: "realtime",
    recommendedFor: "Low-latency voice and realtime interactions",
    contextWindowTokens: 128_000,
    maxOutputTokens: 8_000,
    supportsAudio: true,
    supportsTools: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 4,
    cachedInputUsdPerMillionTokens: 0.4,
    outputUsdPerMillionTokens: 16,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://openai.com/pricing",
  }),

  // --- Anthropic Claude ----------------------------------------------------
  model({
    providerSlug: "anthropic",
    modelId: "claude-fable-5",
    displayName: "Claude Fable 5",
    modelFamily: "claude-5",
    modelTier: "premium",
    recommendedFor: "Creative and long-form writing at top quality",
    contextWindowTokens: 500_000,
    maxOutputTokens: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 5,
    cachedInputUsdPerMillionTokens: 0.5,
    outputUsdPerMillionTokens: 25,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://www.anthropic.com/pricing",
  }),
  model({
    providerSlug: "anthropic",
    modelId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    modelFamily: "claude-opus",
    modelTier: "premium",
    recommendedFor: "Deep reasoning, coding, and complex multi-step work",
    contextWindowTokens: 500_000,
    maxOutputTokens: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 15,
    cachedInputUsdPerMillionTokens: 1.5,
    outputUsdPerMillionTokens: 75,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://www.anthropic.com/pricing",
  }),
  model({
    providerSlug: "anthropic",
    modelId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    modelFamily: "claude-sonnet",
    modelTier: "balanced",
    recommendedFor: "Balanced everyday quality, speed, and cost",
    contextWindowTokens: 500_000,
    maxOutputTokens: 64_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 3,
    cachedInputUsdPerMillionTokens: 0.3,
    outputUsdPerMillionTokens: 15,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://www.anthropic.com/pricing",
  }),
  model({
    providerSlug: "anthropic",
    modelId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    modelFamily: "claude-haiku",
    modelTier: "economy",
    recommendedFor: "Fast, affordable everyday tasks",
    contextWindowTokens: 250_000,
    maxOutputTokens: 32_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 1,
    cachedInputUsdPerMillionTokens: 0.1,
    outputUsdPerMillionTokens: 5,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://www.anthropic.com/pricing",
  }),

  // --- DeepSeek ------------------------------------------------------------
  model({
    providerSlug: "deepseek",
    modelId: "deepseek-v4-flash",
    displayName: "DeepSeek V4 Flash",
    modelFamily: "deepseek-v4",
    modelTier: "economy",
    recommendedFor: "Very low-cost general tasks",
    contextWindowTokens: 128_000,
    maxOutputTokens: 8_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.27,
    cachedInputUsdPerMillionTokens: 0.07,
    outputUsdPerMillionTokens: 1.1,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
  }),
  model({
    providerSlug: "deepseek",
    modelId: "deepseek-v4-pro",
    displayName: "DeepSeek V4 Pro",
    modelFamily: "deepseek-v4",
    modelTier: "reasoning",
    recommendedFor: "Strong reasoning at low cost",
    contextWindowTokens: 128_000,
    maxOutputTokens: 16_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.55,
    cachedInputUsdPerMillionTokens: 0.14,
    outputUsdPerMillionTokens: 2.19,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
  }),

  // --- Moonshot Kimi -------------------------------------------------------
  model({
    providerSlug: "moonshot_kimi",
    modelId: "kimi-k2.6",
    displayName: "Kimi K2.6",
    modelFamily: "kimi-k2",
    modelTier: "balanced",
    recommendedFor: "Long-context general work",
    contextWindowTokens: 256_000,
    maxOutputTokens: 16_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.6,
    cachedInputUsdPerMillionTokens: 0.15,
    outputUsdPerMillionTokens: 2.5,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://platform.moonshot.ai/docs/pricing",
  }),
  model({
    providerSlug: "moonshot_kimi",
    modelId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    modelFamily: "kimi-k2",
    modelTier: "coding",
    recommendedFor: "Coding and technical tasks",
    contextWindowTokens: 256_000,
    maxOutputTokens: 32_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.6,
    cachedInputUsdPerMillionTokens: 0.15,
    outputUsdPerMillionTokens: 2.5,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://platform.moonshot.ai/docs/pricing",
  }),
  model({
    providerSlug: "moonshot_kimi",
    modelId: "kimi-k2.7-code-highspeed",
    displayName: "Kimi K2.7 Code High-Speed",
    modelFamily: "kimi-k2",
    modelTier: "coding",
    recommendedFor: "Faster coding responses at higher cost",
    contextWindowTokens: 256_000,
    maxOutputTokens: 32_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 1,
    cachedInputUsdPerMillionTokens: 0.25,
    outputUsdPerMillionTokens: 3,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://platform.moonshot.ai/docs/pricing",
  }),

  // --- Groq / Llama --------------------------------------------------------
  model({
    providerSlug: "groq",
    modelId: "meta-llama/llama-4-scout-17b-16e-instruct",
    displayName: "Llama 4 Scout 17B (Groq)",
    modelFamily: "llama-4",
    modelTier: "private_open",
    recommendedFor: "Fast open-weight model on Groq hardware",
    contextWindowTokens: 128_000,
    maxOutputTokens: 8_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.11,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 0.34,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://groq.com/pricing",
  }),
  model({
    providerSlug: "groq",
    modelId: "llama-3.3-70b-versatile",
    displayName: "Llama 3.3 70B Versatile (Groq)",
    modelFamily: "llama-3",
    modelTier: "private_open",
    recommendedFor: "Capable open-weight model with low latency",
    contextWindowTokens: 128_000,
    maxOutputTokens: 32_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.59,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 0.79,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://groq.com/pricing",
  }),
  model({
    providerSlug: "groq",
    modelId: "llama-3.1-8b-instant",
    displayName: "Llama 3.1 8B Instant (Groq)",
    modelFamily: "llama-3",
    modelTier: "economy",
    recommendedFor: "Ultra-cheap, ultra-fast lightweight tasks",
    contextWindowTokens: 128_000,
    maxOutputTokens: 8_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.05,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 0.08,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://groq.com/pricing",
  }),

  // --- Google Gemini -------------------------------------------------------
  model({
    providerSlug: "google_gemini",
    modelId: "gemini-3.1-flash-lite",
    displayName: "Gemini 3.1 Flash Lite",
    modelFamily: "gemini-3",
    modelTier: "economy",
    recommendedFor: "Fast, affordable multimodal tasks",
    contextWindowTokens: 1_000_000,
    maxOutputTokens: 64_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 0.1,
    cachedInputUsdPerMillionTokens: 0.025,
    outputUsdPerMillionTokens: 0.4,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://ai.google.dev/pricing",
  }),
  model({
    providerSlug: "google_gemini",
    modelId: "gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro (Preview)",
    modelFamily: "gemini-3",
    modelTier: "premium",
    recommendedFor: "Large-context, high-quality multimodal reasoning",
    contextWindowTokens: 2_000_000,
    maxOutputTokens: 64_000,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    supportsCaching: true,
    inputUsdPerMillionTokens: 1.25,
    cachedInputUsdPerMillionTokens: 0.31,
    outputUsdPerMillionTokens: 10,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://ai.google.dev/pricing",
  }),

  // --- Fireworks (open models, OpenAI-compatible) --------------------------
  model({
    providerSlug: "fireworks",
    modelId: "accounts/fireworks/models/kimi-k2.6",
    displayName: "Kimi K2.6 (Fireworks)",
    modelFamily: "kimi-k2",
    modelTier: "private_open",
    recommendedFor: "Open-weight Kimi hosted on Fireworks",
    contextWindowTokens: 256_000,
    maxOutputTokens: 16_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.6,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 2.5,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://fireworks.ai/pricing",
  }),
  model({
    providerSlug: "fireworks",
    modelId: "accounts/fireworks/models/kimi-k2p7-code",
    displayName: "Kimi K2.7 Code (Fireworks)",
    modelFamily: "kimi-k2",
    modelTier: "coding",
    recommendedFor: "Open-weight coding model hosted on Fireworks",
    contextWindowTokens: 256_000,
    maxOutputTokens: 32_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.7,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 2.8,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://fireworks.ai/pricing",
  }),
  model({
    providerSlug: "fireworks",
    modelId: "accounts/fireworks/models/deepseek-v4-flash",
    displayName: "DeepSeek V4 Flash (Fireworks)",
    modelFamily: "deepseek-v4",
    modelTier: "economy",
    recommendedFor: "Low-cost open model hosted on Fireworks",
    contextWindowTokens: 128_000,
    maxOutputTokens: 8_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.3,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 1.2,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://fireworks.ai/pricing",
  }),
  model({
    providerSlug: "fireworks",
    modelId: "accounts/fireworks/models/deepseek-v4-pro",
    displayName: "DeepSeek V4 Pro (Fireworks)",
    modelFamily: "deepseek-v4",
    modelTier: "reasoning",
    recommendedFor: "Open reasoning model hosted on Fireworks",
    contextWindowTokens: 128_000,
    maxOutputTokens: 16_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputUsdPerMillionTokens: 0.6,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 2.4,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://fireworks.ai/pricing",
  }),
  model({
    providerSlug: "fireworks",
    modelId: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    displayName: "Llama 3.3 70B (Fireworks)",
    modelFamily: "llama-3",
    modelTier: "private_open",
    recommendedFor: "General open-weight model hosted on Fireworks",
    contextWindowTokens: 128_000,
    maxOutputTokens: 16_000,
    supportsTools: true,
    supportsJson: true,
    supportsStreaming: true,
    inputUsdPerMillionTokens: 0.9,
    cachedInputUsdPerMillionTokens: null,
    outputUsdPerMillionTokens: 0.9,
    pricingNotes: PRICING_NOTE,
    pricingSourceUrl: "https://fireworks.ai/pricing",
  }),
];

/** Providers keyed by slug for quick lookup. */
export const PROVIDERS_BY_SLUG: Record<string, ModelProvider> = Object.fromEntries(
  MODEL_PROVIDERS.map((p) => [p.slug, p]),
);

/** Models keyed by their globally-unique modelId. */
export const MODELS_BY_ID: Record<string, AiModel> = Object.fromEntries(
  AI_MODELS.map((m) => [m.modelId, m]),
);

export function getProvider(slug: ProviderSlug): ModelProvider | null {
  return PROVIDERS_BY_SLUG[slug] ?? null;
}

export function getModel(modelId: string): AiModel | null {
  return MODELS_BY_ID[modelId] ?? null;
}

export function modelsByProvider(slug: ProviderSlug): AiModel[] {
  return AI_MODELS.filter((m) => m.providerSlug === slug);
}
